# Generated by Django 5.0.3 on 2024-09-03 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_enquriy',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
